"""DNS zone file generation."""

from infomaniak.api import api_request
from infomaniak.config import get_token
from infomaniak.output import bold, dim, green


def cmd_dns_zone(args):
    """Generate a BIND-format zone file for a domain."""
    token = get_token()
    domain = args.domain

    data = api_request("GET", f"/2/zones/{domain}/records", token)
    records = data.get("data", [])

    if not records:
        print(f"  {dim(f'No DNS records found for {domain}.')}")
        return

    lines = []
    lines.append(f"; Zone file for {domain}")
    lines.append(f"; Generated by infomaniak-cli")
    lines.append(f"; {len(records)} records")
    lines.append(f"")
    lines.append(f"$ORIGIN {domain}.")
    lines.append(f"$TTL 3600")
    lines.append(f"")

    # Sort: SOA first, then NS, then others
    type_order = {"SOA": 0, "NS": 1, "MX": 2, "A": 3, "AAAA": 4, "CNAME": 5, "TXT": 6}
    records.sort(key=lambda r: (type_order.get(r.get("type", ""), 99), r.get("source", "")))

    for r in records:
        rtype = r.get("type", "")
        source = r.get("source", "@")
        if source == ".":
            source = "@"
        target = r.get("target", "")
        ttl = r.get("ttl", 3600)

        # Format source — BIND uses @ for zone apex
        name = source if source != "@" else "@"

        # Format target — add trailing dot for FQDNs
        if rtype in ("CNAME", "NS", "MX", "SRV", "PTR"):
            if target and not target.endswith("."):
                target = f"{target}."
        elif rtype == "TXT":
            # Ensure TXT values are quoted
            if not target.startswith('"'):
                target = f'"{target}"'

        line = f"{name:<24} {ttl:<8} IN  {rtype:<8} {target}"
        lines.append(line)

    zone_content = "\n".join(lines) + "\n"

    if args.output:
        from pathlib import Path
        outpath = Path(args.output)
        outpath.write_text(zone_content)
        print(f"\n  {green('Exported zone file to')} {bold(str(outpath))}\n")
    else:
        print(zone_content)
