import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'Infomaniak SDK for Python',
  description: 'Python SDK documentation for the Infomaniak API.',
  srcDir: 'src',
  base: process.env.NODE_ENV === 'production' ? '/infomaniak/' : '/',
  cleanUrls: true,
  themeConfig: {
    socialLinks: [{ icon: 'github', link: 'https://github.com/XLongLink/infomaniak' }],
    sidebar: [
      {
        text: 'AI',
        collapsed: true,
        items: [{ text: 'Overview', link: '/ai/' }],
      },
      {
        text: 'Backup',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/backup/' },
          { text: 'Product', link: '/backup/product' },
          { text: 'Slots', link: '/backup/slots' },
          { text: 'Administrator', link: '/backup/administrator' },
          { text: 'Passwords', link: '/backup/passwords' },
          { text: 'Billing', link: '/backup/billing' },
        ],
      },
      {
        text: 'Cloud',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/cloud/' },
          {
            text: 'Database',
            collapsed: true,
            items: [
              { text: 'Overview', link: '/cloud/database' },
              { text: 'Database Backups', link: '/cloud/database/backups' },
              { text: 'Database Scheduled', link: '/cloud/database/scheduled' },
              { text: 'Database Config', link: '/cloud/database/config' },
              { text: 'Database Data', link: '/cloud/database/data' },
              { text: 'Database IP', link: '/cloud/database/ip' },
              { text: 'Database Restore', link: '/cloud/database/restore' },
            ],
          },
        ],
      },
      {
        text: 'Core',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/core/' },
          { text: 'Actions', link: '/core/actions' },
          { text: 'Countries', link: '/core/countries' },
          { text: 'Events', link: '/core/events' },
          { text: 'kSuite', link: '/core/ksuite' },
          { text: 'kSuite Mailbox', link: '/core/ksuite/mailbox' },
          { text: 'Languages', link: '/core/languages' },
          { text: 'Profile', link: '/core/profile' },
          { text: 'Profile Password', link: '/core/profile/password' },
          { text: 'Profile Email', link: '/core/profile/email' },
          { text: 'Profile Phone', link: '/core/profile/phone' },
          { text: 'Profile Avatar', link: '/core/profile/avatar' },
          { text: 'Profile Info', link: '/core/profile/info' },
          { text: 'Products', link: '/core/products' },
          { text: 'Tasks', link: '/core/tasks' },
          { text: 'Timezones', link: '/core/timezones' },
          { text: 'User', link: '/core/user' },
          { text: 'User Accounts', link: '/core/user/accounts' },
          { text: 'User Teams', link: '/core/user/teams' },
        ],
      },
      {
        text: 'DNS',
        collapsed: true,
        items: [{ text: 'Overview', link: '/dns/' }],
      },
      {
        text: 'kChat',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/kchat/' },
          { text: 'Users', link: '/kchat/users' },
          { text: 'Bots', link: '/kchat/bots' },
          { text: 'Teams', link: '/kchat/teams' },
          { text: 'Channels', link: '/kchat/channels' },
          { text: 'Posts', link: '/kchat/posts' },
          { text: 'Threads', link: '/kchat/threads' },
          { text: 'Files', link: '/kchat/files' },
          { text: 'Preferences', link: '/kchat/preferences' },
          { text: 'Status', link: '/kchat/status' },
          { text: 'Emoji', link: '/kchat/emoji' },
          { text: 'Reactions', link: '/kchat/reactions' },
          { text: 'Webhooks', link: '/kchat/webhooks' },
          { text: 'Commands', link: '/kchat/commands' },
          { text: 'System', link: '/kchat/system' },
          { text: 'Groups', link: '/kchat/groups' },
          { text: 'Roles', link: '/kchat/roles' },
          { text: 'Insights', link: '/kchat/insights' },
        ],
      },
      {
        text: 'kDrive',
        collapsed: true,
        items: [{ text: 'Overview', link: '/kdrive/' }],
      },
      {
        text: 'kMeet',
        collapsed: true,
        items: [
          { text: 'Overview', link: '/kmeet/' },
          { text: 'Plan', link: '/kmeet/plan' },
          { text: 'Room', link: '/kmeet/room' },
        ],
      },
      {
        text: 'Mail',
        collapsed: true,
        items: [{ text: 'Overview', link: '/mail/' }],
      },
      {
        text: 'Newsletter',
        collapsed: true,
        items: [{ text: 'Overview', link: '/newsletter/' }],
      },
      {
        text: 'Radio',
        collapsed: true,
        items: [{ text: 'Overview', link: '/radio/' }],
      },
      {
        text: 'Tickets',
        collapsed: true,
        items: [{ text: 'Overview', link: '/tickets/' }],
      },
      {
        text: 'URL',
        collapsed: true,
        items: [{ text: 'Overview', link: '/url/' }],
      },
      {
        text: 'Video',
        collapsed: true,
        items: [{ text: 'Overview', link: '/video/' }],
      },
      {
        text: 'VOD',
        collapsed: true,
        items: [{ text: 'Overview', link: '/vod/' }],
      },
    ],
    search: {
      provider: 'local',
    },
  },
})
